# Erhöht die Bluetooth-Sendeleistung für bessere Reichweite
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# USB-Unterstützung (falls du mal am Kabel hängst)
CONFIG_ZMK_USB=y

# Bluetooth ist bei ZMK standardmäßig IMMER an, 
# solange wir es nicht explizit ausschalten.
